# 05 — Exploratory Plotting and Statistical Handoff

#This notebook performs exploratory visualization of spatial cell-type abundance estimates derived from the SpaceJam / Cell2Location workflow.

#The goal is to:

#- confirm ROI metadata structure
#- visualize inferred cell-type proportions
#- inspect disease-, pathology-, and region-associated trends
#- generate quick non-parametric screening results
#- export clean inputs for formal R-based mixed-effects modeling

#Formal statistical inference is performed in R using beta mixed-effects models.

import matplotlib.pyplot as plt
import seaborn as sns

from python.plotting_utils import (
    load_abundance_tables,
    summarize_roi_counts,
    plot_celltype_by_group,
    plot_celltype_by_pathology_and_disease,
    plot_celltype_by_region_and_disease,
    plot_mean_composition_stacked,
    run_mannwhitney_screen
)

sns.set(style="whitegrid", context="talk")
plt.rcParams["pdf.fonttype"] = 42

## Load abundance tables

# These tables are generated by `04_extract_cell_proportions.ipynb`.

wide_file = "results/cell_proportions/cell2location_abundance_wide_with_meta.csv"
long_file = "results/cell_proportions/cell2location_abundance_long_rel.csv"

df_wide, df_long = load_abundance_tables(
    wide_file=wide_file,
    long_file=long_file
)

print(df_wide.shape)
df_long.head()

## ROI count sanity check

summarize_roi_counts(
    df_long,
    roi_col="ROI",
    group_col="disease_status"
)

## Plot selected cell types by disease status

for ct in ["Microglia1", "Astrocytes1", "Endothelial"]:
    plot_celltype_by_group(
        df_long,
        celltype=ct,
        group="disease_status",
        save_file=f"figures/exploratory/{ct}_by_disease_status.pdf"
    )

## Plot selected cell types by pathology and disease status

for ct in ["Oligodendrocytes1", "SMC"]:
    plot_celltype_by_pathology_and_disease(
        df_long,
        celltype=ct,
        save_file=f"figures/exploratory/{ct}_by_pathology_disease.pdf"
    )

## Plot selected cell types by region and disease status
plot_celltype_by_region_and_disease(
    df_long,
    celltype="Microglia3",
    save_file="figures/exploratory/Microglia3_by_region_disease.pdf"
)

## Mean cell-type composition by disease status
mean_composition = plot_mean_composition_stacked(
    df_long,
    group_col="disease_status",
    save_file="figures/exploratory/mean_celltype_composition_by_disease.pdf"
)

mean_composition
## Quick exploratory non-parametric screen

#This is not the final statistical model. It is only used to identify trends before formal mixed-effects modeling.
stats_df = run_mannwhitney_screen(
    df_long,
    group_col="disease_status",
    group_1="AD-CAA",
    group_2="Control",
    abundance_col="rel_abundance",
    min_n=5
)

stats_df.to_csv(
    "results/cell_proportions/celltype_disease_stats_mannwhitney.csv",
    index=False
)

stats_df.head(10)

## Export analysis-ready table for R

#The long-format table is used for beta mixed-effects models in R.

#Formal model:

```r
rel_abundance ~ contrast_variable + (1 | Scan_ID)
```
# with :
``` r
glmmTMB::beta_family(link = "logit")
```
df_long.to_csv(
    "results/cell_proportions/spatial_celltype_proportions_for_R.csv",
    index=False
)
